[server]
port = 8501
address = "127.0.0.1"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 10000


[theme]
base = "dark"
backgroundColor = "#0a0a10"
secondaryBackgroundColor = "#13131e"
textColor = "#F8FAFC"
primaryColor = "#8B5CF6"
font = "sans serif"
